# Generated by Django 3.2.5 on 2022-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210727_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='files/', verbose_name='Capa do post'),
        ),
    ]
